<?php require __DIR__.'/config.php';
$action=$_GET['action']??'';
if($action==='login' && $_SERVER['REQUEST_METHOD']==='POST'){ $in=json_decode(file_get_contents('php://input'),true)??$_POST; if(($in['user']??'')===ADMIN_USER && ($in['pass']??'')===ADMIN_PASS){$_SESSION['admin']=true; json_response(['ok'=>true]);} json_response(['ok'=>false,'error'=>'Usuário ou senha inválidos.'],401); }
if($action==='logout'){session_destroy(); json_response(['ok'=>true]);}
if(!logged()) json_response(['ok'=>false,'error'=>'Não autenticado.'],401);
if($action==='settings' && $_SERVER['REQUEST_METHOD']==='POST'){ $in=json_decode(file_get_contents('php://input'),true)??[]; $old=settings(); foreach(['name','city','phone','instagram','facebook','address','hours','about'] as $k) if(isset($in[$k])) $old[$k]=trim((string)$in[$k]); write_json(DATA_DIR.'/settings.json',$old); json_response(['ok'=>true,'settings'=>$old]); }
if($action==='gallery' && $_SERVER['REQUEST_METHOD']==='POST'){ if(empty($_FILES['photo'])||$_FILES['photo']['error']!==UPLOAD_ERR_OK) json_response(['ok'=>false,'error'=>'Selecione uma imagem válida.'],400); $f=$_FILES['photo']; if($f['size']>6*1024*1024) json_response(['ok'=>false,'error'=>'Imagem maior que 6 MB.'],400); $mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']); $map=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif']; if(!isset($map[$mime])) json_response(['ok'=>false,'error'=>'Formato permitido: JPG, PNG, WEBP ou GIF.'],400); $name=bin2hex(random_bytes(8)).'.'.$map[$mime]; if(!move_uploaded_file($f['tmp_name'],GALLERY_DIR.'/'.$name)) json_response(['ok'=>false,'error'=>'Não foi possível salvar a imagem.'],500); $items=gallery(); $item=['id'=>bin2hex(random_bytes(6)),'url'=>'uploads/gallery/'.$name,'title'=>trim($_POST['title']??''),'created_at'=>date('c')]; $items[]=$item; write_json(DATA_DIR.'/gallery.json',$items); json_response(['ok'=>true,'item'=>$item]); }
if($action==='gallery_delete' && $_SERVER['REQUEST_METHOD']==='POST'){ $in=json_decode(file_get_contents('php://input'),true)??[]; $items=gallery(); $new=[]; $deleted=false; foreach($items as $x){if(($x['id']??'')===($in['id']??'')){ $path=__DIR__.'/'.$x['url']; if(is_file($path)) @unlink($path); $deleted=true; continue;} $new[]=$x;} write_json(DATA_DIR.'/gallery.json',$new); json_response(['ok'=>$deleted]); }
if($action==='appointments'){ json_response(['ok'=>true,'items'=>array_reverse(appointments())]); }
json_response(['ok'=>false,'error'=>'Ação inválida.'],404);
